// src/components/InvoicePaperPreview.tsx
import React from 'react';
import { View } from 'react-native';
import { Text } from 'react-native-paper';
import { Invoice } from '../types';

interface Props {
  invoice: Invoice;
  fallbackIssuerName?: string;
  fallbackIssuerEmail?: string;
}

export default function InvoicePaperPreview({
  invoice,
  fallbackIssuerName = 'Concrete Pumping',
  fallbackIssuerEmail = '',
}: Props) {
  const issuerName = invoice.issuerName || fallbackIssuerName;
  const issuerEmail = invoice.issuerEmail || fallbackIssuerEmail;

  return (
    <View style={styles.paper}>
      <View style={styles.topRow}>
        <View style={styles.companyBlock}>
          <Text style={styles.company}>{issuerName}</Text>
          {!!issuerEmail && <Text style={styles.small}>{issuerEmail}</Text>}
        </View>
        <View style={styles.invoiceBlock}>
          <Text style={styles.invoiceLabel}>INVOICE</Text>
          <Text style={styles.invoiceNumber}>{invoice.invoiceNumber}</Text>
        </View>
      </View>

      <InfoRow label="Customer" value={invoice.clientName} rightLabel="Date" rightValue={invoice.date} />
      <InfoRow label="Job Address" value={invoice.jobAddress || ''} wide />
      <InfoRow label="Phone" value={invoice.clientPhone || ''} rightLabel="Due Date" rightValue={invoice.dueDate || ''} />
      <InfoRow label="Billing Address" value={invoice.clientAddress || ''} wide />

      <View style={styles.serviceRow}>
        <Service label="RMC" value={invoice.rmc || ''} />
        <Service label="Due" value={invoice.dueTime || ''} />
        <Service label="Arrive" value={invoice.arriveTime || ''} />
        <Service label="Start" value={invoice.startTime || ''} />
        <Service label="Finish" value={invoice.finishTime || ''} last />
      </View>

      {!!invoice.jobReferences?.length && (
        <View>
          <Text style={styles.sectionTitle}>JOB / PO REFERENCES</Text>
          <View style={styles.tableHeader}>
            <Text style={[styles.cell, styles.flexDate]}>Date</Text>
            <Text style={[styles.cell, styles.flexSite]}>Job / Site</Text>
            <Text style={[styles.cell, styles.flexRef]}>Job #</Text>
            <Text style={[styles.cell, styles.flexRef, styles.lastCell]}>PO #</Text>
          </View>
          {invoice.jobReferences.map(ref => (
            <View key={ref.jobId} style={styles.tableRow}>
              <Text style={[styles.cell, styles.flexDate]}>{ref.date || ''}</Text>
              <Text style={[styles.cell, styles.flexSite]}>{ref.address || ''}</Text>
              <Text style={[styles.cell, styles.flexRef]}>{ref.jobNumber || ''}</Text>
              <Text style={[styles.cell, styles.flexRef, styles.lastCell]}>{ref.poNumber || ''}</Text>
            </View>
          ))}
        </View>
      )}

      <View style={styles.tableHeader}>
        <Text style={[styles.cell, styles.qty]}>Qty.</Text>
        <Text style={[styles.cell, styles.description]}>Description</Text>
        <Text style={[styles.cell, styles.money]}>Unit Price</Text>
        <Text style={[styles.cell, styles.money, styles.lastCell]}>Amount</Text>
      </View>

      {(invoice.lineItems || []).map(item => (
        <View key={item.id} style={styles.tableRow}>
          <Text style={[styles.cell, styles.qty, styles.center]}>{item.quantity}</Text>
          <Text style={[styles.cell, styles.description]}>{item.description}</Text>
          <Text style={[styles.cell, styles.money, styles.right]}>{'$' + Number(item.rate || 0).toFixed(2)}</Text>
          <Text style={[styles.cell, styles.money, styles.right, styles.lastCell]}>{'$' + Number(item.amount || 0).toFixed(2)}</Text>
        </View>
      ))}

      <View style={styles.bottomRow}>
        <View style={styles.terms}>
          <Text style={styles.bold}>Terms / Notes</Text>
          {!!invoice.terms && <Text style={styles.small}>{invoice.terms}</Text>}
          {!!invoice.notes && <Text style={styles.small}>{invoice.notes}</Text>}
        </View>
        <View style={styles.totals}>
          <TotalRow label="Subtotal" value={invoice.subtotal || 0} />
          {!!invoice.tax && <TotalRow label="Tax" value={invoice.tax} />}
          <View style={styles.grandRow}>
            <Text style={styles.grand}>Total</Text>
            <Text style={styles.grand}>{'$' + Number(invoice.total || 0).toFixed(2)}</Text>
          </View>
        </View>
      </View>

      <View style={styles.signature}>
        <Text style={styles.small}>Authorized Signature ______________________________</Text>
        <Text style={styles.fine}>Generated by PumpTracker. Payment terms and business policies are set by the issuing business.</Text>
      </View>
    </View>
  );
}

function InfoRow({
  label,
  value,
  rightLabel,
  rightValue,
  wide,
}: {
  label: string;
  value: string;
  rightLabel?: string;
  rightValue?: string;
  wide?: boolean;
}) {
  return (
    <View style={styles.infoRow}>
      <View style={styles.labelBox}><Text style={styles.labelText}>{label}</Text></View>
      <View style={[styles.valueBox, wide && styles.wideValue]}><Text style={styles.valueText}>{value}</Text></View>
      {!wide && (
        <>
          <View style={styles.labelBox}><Text style={styles.labelText}>{rightLabel || ''}</Text></View>
          <View style={styles.valueBox}><Text style={styles.valueText}>{rightValue || ''}</Text></View>
        </>
      )}
    </View>
  );
}

function Service({ label, value, last }: { label: string; value: string; last?: boolean }) {
  return (
    <View style={[styles.service, last && styles.lastCell]}>
      <Text style={styles.serviceLabel}>{label}</Text>
      <Text style={styles.small}>{value}</Text>
    </View>
  );
}

function TotalRow({ label, value }: { label: string; value: number }) {
  return (
    <View style={styles.totalRow}>
      <Text style={styles.small}>{label}</Text>
      <Text style={styles.bold}>{'$' + Number(value || 0).toFixed(2)}</Text>
    </View>
  );
}

const border = '#111';

const styles: any = {
  paper: {
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: border,
    marginBottom: 16,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
    borderBottomWidth: 2,
    borderBottomColor: border,
  },
  companyBlock: { flex: 1, paddingRight: 10 },
  company: { fontSize: 22, fontWeight: '800', color: '#111' },
  invoiceBlock: { alignItems: 'flex-end' },
  invoiceLabel: { fontSize: 11, fontWeight: '700', color: '#111' },
  invoiceNumber: { fontSize: 20, fontWeight: '800', color: '#111' },
  small: { fontSize: 11, color: '#222', marginTop: 3 },
  bold: { fontSize: 11, color: '#111', fontWeight: '700' },
  infoRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: border, minHeight: 36 },
  labelBox: { width: 88, padding: 7, backgroundColor: '#f3f3f3', justifyContent: 'center' },
  labelText: { fontSize: 10, fontWeight: '700', color: '#111' },
  valueBox: { flex: 1, padding: 7, justifyContent: 'center' },
  wideValue: { flex: 1 },
  valueText: { fontSize: 11, color: '#111' },
  serviceRow: { flexDirection: 'row', borderBottomWidth: 2, borderBottomColor: border },
  service: { flex: 1, paddingVertical: 7, paddingHorizontal: 4, alignItems: 'center', borderRightWidth: 1, borderRightColor: border },
  serviceLabel: { fontSize: 9, fontWeight: '700', color: '#111', textTransform: 'uppercase' },
  sectionTitle: { fontSize: 10, fontWeight: '800', color: '#111', paddingHorizontal: 7, paddingTop: 7, paddingBottom: 4 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#efefef', borderBottomWidth: 1, borderBottomColor: border },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: border },
  cell: { padding: 6, fontSize: 9, color: '#111', borderRightWidth: 1, borderRightColor: border },
  lastCell: { borderRightWidth: 0 },
  qty: { width: 45 },
  description: { flex: 1 },
  money: { width: 72 },
  flexDate: { flex: 0.9 },
  flexSite: { flex: 1.8 },
  flexRef: { flex: 0.9 },
  center: { textAlign: 'center' },
  right: { textAlign: 'right' },
  bottomRow: { flexDirection: 'row', minHeight: 100 },
  terms: { flex: 1, padding: 9, borderRightWidth: 1, borderRightColor: border },
  totals: { width: 175 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', padding: 8, borderBottomWidth: 1, borderBottomColor: border },
  grandRow: { flexDirection: 'row', justifyContent: 'space-between', padding: 9 },
  grand: { fontSize: 15, fontWeight: '800', color: '#111' },
  signature: { padding: 10, borderTopWidth: 2, borderTopColor: border },
  fine: { fontSize: 8, color: '#333', marginTop: 6 },
};
